# Site settings
title: Creanyx Blog
email: shakee@creanyx.com
description: "...."
baseurl: ""
url: "http://creanyx.github.io"
twitter_username: creanyx
github_username:  creanyx

# Build settings
markdown: kramdown
permalink: pretty
